### ISSUE TITLE
Please keep your former projects privately or delete them

### ISSUE THREAD

**Issue by emilygrande** [BU-CS673/bubolo#399]
Hi, this is emily, TA for MET CS program.

Could you please keep your former projects privately or delete them ? I am afraid that someone has used your code for their projects...

Thanks a lot !

**Comment by ChristopherCanfield** [comment]
Hi Emily,

Sorry, no. We received permission to open source this right from the start. Ron Czik, who looks to be the professor this semester, was also the professor when we took the course.

Anyone can legally make use of our code according to the license we selected. However, if using our code violates your class requirements, you have plenty of ways to address that. I had to deal with the same thing when I was a TA in the MET CS program, and I still have to deal with it now that I am a course facilitator for the department.

It would be one thing if our project was simply homework, with direct answers, but it wasn't. The project idea was entirely our own, as was the design and implementation. I and many of the other members of my team treated this as a capstone project, and devoted extremely large amounts of time to creating something far larger than what the class required.

Anyway, taking down our project would not resolve the underlying issue. If you have students who want to cheat, there are thousands of other programs that they could simply copy. You need to address their cheating directly.

If you would like to discuss this further, please contact me via email. You can find my email address using the BU directory (I'd rather not post it here).

Regards,
Christopher Canfield

**Comment by Nesciosquid** [comment]
I second all of Chris's sentiments. This project is open source and it will
stay that way.

Good luck with teaching!
